services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traffic
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Проверяем готовность базы каждые 5 секунд
      test: ["CMD-SHELL", "pg_isready -U postgres -d traffic"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./files:/app/files
    environment:
      - GIN_MODE=release
      - DB_DSN=host=postgres user=postgres password=postgres dbname=traffic port=5432 sslmode=disable TimeZone=UTC
    depends_on:
      postgres:
        condition: service_healthy # Бэк ждет БД

  frontend:
    build:
      context: ./frontend/traffic-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started # Фронт ждет запуска бэкенда
volumes:
  postgres_data: